### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by j143** [j143/social#1]
```
social\internal\graph\graph_test.go:35: Expected 1 connection for user 1, got 0
--- FAIL: TestGraph_AddConnection (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 6 [running]:
testing.tRunner.func1.2({0x2d54a0, 0xc0000101c8})
        C:/Program Files/Go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        C:/Program Files/Go/src/testing/testing.go:1392 +0x39f
panic({0x2d54a0, 0xc0000101c8})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
social/internal/graph.TestGraph_AddConnection(0xc0000b6000)
        d:/repo/social-media-analysis/internal/graph/graph_test.go:38 +0x84c
testing.tRunner(0xc0000b6000, 0x2ed3b8)
        C:/Program Files/Go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1486 +0x35f
```

**Comment by j143** [comment]
test case error. Bidirectional connections are required in this specific case

https://github.com/j143/social/commit/123a60beb9cc1131c80a8c250969512f29b567e5
