### ISSUE TITLE
invalid memory address or nil pointer dereference signal 0xc0000005 code=0x0 addr=0x8 pc=0x5eb911

### ISSUE THREAD

**Issue by j143** [j143/social#2]
> go run .\utils\preprocessing.go
2023/07/16 13:43:42 User ID 215 not found in the graph
2023/07/16 13:43:42 User ID 209 not found in the graph
2023/07/16 13:43:42 User ID 74 not found in the graph 
2023/07/16 13:43:42 User ID 292 not found in the graph
2023/07/16 13:43:42 User ID 114 not found in the graph
2023/07/16 13:43:42 User ID 15 not found in the graph 
2023/07/16 13:43:42 User ID 37 not found in the graph 
2023/07/16 13:43:42 User ID 210 not found in the graph
2023/07/16 13:43:42 User ID 12 not found in the graph
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x5eb911]

goroutine 1 [running]:
main.testUserConnections(0x608a84?)
        ./utils/preprocessing.go:141 +0x31
main.main()
        ./utils/preprocessing.go:133 +0x6f
exit status 2

**Comment by j143** [comment]
**Solution:**

I was trying access element which does not exists, due to non sequential elements.

graph[0] does not exists, while graph[190] exists.
